### ISSUE TITLE
怎么获取QQ音乐的cookies呢？

### ISSUE THREAD

**Issue by Hiddensu** [feeluown/feeluown-qqmusic#6]
求个教程

**Comment by cosven** [comment]
你是什么浏览器呢？以 chrome 为例的话

1. 打开 qq 音乐网站
2. 登录
3. 在网页上鼠标右键，点击「检查元素」（英文叫 Inspec）。或者直接按 F12。就会看到类似这样的窗口
![image](https://user-images.githubusercontent.com/4962134/94247236-6cbc4b00-ff4f-11ea-94b2-c64ff5679ec0.png)
4. 点击「网络」（英文叫 Network）
![image](https://user-images.githubusercontent.com/4962134/94247417-ad1bc900-ff4f-11ea-87df-518c74f35513.png)
5. 拷贝 cookies，复制到 feeluown 的登录窗口

**Comment by cosven** [comment]
最新版的话，可以安装 `PyQtWebEngine` 包，然后使用”网页登录“功能。先 close。
